name: Build & publish Next.js site to Github Pages

on:
  workflow_dispatch: # Manually run from the Actions tab
  push:
    tags:        
      - '**/release'
      - '**/test'

# Environment variables
env:
  websitePath: src/website
  commitMsg: Publishing update

# Allow only one concurrent deployment
concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  # Publishing website
  publish:
    permissions:
      pages: write
      contents: read
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    outputs:
      workingPath: ${{ steps.dir.outputs.workingPath }}
    needs: build
    steps:
    
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ steps.dir.outputs.working }}/web

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4